name: my_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mlflow
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - optuna
  - catboost
  - streamlit
  - langchain
  - openai
  - pypdf
  - langchain-experimental
  - pip
  - pip:
      - langchain_community
      - langchain_openai
      - streamlit_chat
      - sentence_transformers
      - chromadb
      - tiktoken
      - langchain_chroma
      - langchain-experimental
      - tabulate
